package com.shadai.petclinic.model;

public enum Breed {
    AKITA,
    ALASKAN_MALAMUTE,
    AUSTRALIAN_SHEPHERD,
    TERRIER,
    BASSET_HOUND,
    BEAGLE,
    BEARDED_COLLIE,
    BLOODHOUND,
    BORDER_COLLIE,
    BULL_TERRIER,
    BULLDOG,
    CHIHUAHUA,
    CROW,
    ABBOTT,
    PARROT,
    EAGLE,
    WHISTLINH_KITE,
    GEKO,
    COCODRILE,
    HAMSTER,
    MOUSE,
    PERSIAN,
    MAINE_COON,
    SPHYNX,
    ABYSSINIAN,
    DEVON_REX,
    NA,
}
